### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lijunzh** [zhulingchen/SSSI#2]
@zhulingchen Ghassan is asking for this Python wrapper. Here are some thoughts I had to make it a two-phase project.

1. Native python wrapper. Python can call matlab function directly as long as matlab is installed. This can give a dependable python API that requires user to have matlab install. The advantage is that we can get this our fairly quickly.

2. C-lib+ python/matlab wrapper. In the long run, I want to rewrite the mex file into a C-lib or Rust-lib and offer python/matlab wrapper for that lib. This approach is most flexible but requires more work.

**Comment by zhulingchen** [comment]
Personally, I prefer (2) as a thorough solution. But if Ghassan needs it quickly, then it is also fine to finish (1) first, depending on how much free time you could have (I know you must be quite busy now).

**Comment by lijunzh** [comment]
I totally agree with you. My plan was to do (2) later this year when I finish the early submission season before May. But Ghassan wants some deliverables to the sponsor, so I will try to do the seemingly useless work of (1).

**Comment by zhulingchen** [comment]
OK. Thank you very much for the further contribution and I really appreciate that!
